#!/bin/sh

rm -f src/compression_tools/blosc/libblosc.a
rm -f src/compression_tools/blosc/lib/blosc-*/*.o
rm -f src/compression_tools/blosc/lib/snappy-*/*.o
rm -f src/compression_tools/blosc/lib/lz4-*/*.o
rm -f src/compression_tools/zstd/*.o 
rm -f src/compression_tools/zstd/common/*.o 
rm -f src/compression_tools/zstd/compress/*.o 
rm -f src/compression_tools/zstd/decompress/*.o

rm -f src/Makevars
