#' @importFrom grumpy convert_bytes_to_array
codec_bytes_decode <- function(
  input,
  chunk_dim,
  datatype,
  endian,
  ...
) {
  convert_bytes_to_array(
    input,
    datatype$base_type,
    chunk_dim,
    datatype$nbytes,
    endian
  )
}

codec_bytes_encode <- function(input, datatype, endian) {
  if (is.character(input)) {
    ## we need to create fixed length strings either via padding or trimming
    if (datatype$base_type == "unicode") {
      to <- ifelse(endian == "little", "UCS-4LE", "UCS-4BE")
      raw_list <- iconv(input, to = to, toRaw = TRUE)
    } else {
      raw_list <- iconv(input, toRaw = TRUE)
    }
    unlist(
      lapply(
        raw_list,
        FUN = function(x, nbytes) {
          # NULL generated by iconv() for NA_character_
          if (is.null(x)) {
            x <- writeBin(NA_integer_, raw())
          }
          length(x) <- nbytes
          return(x)
        },
        nbytes = datatype$nbytes
      )
    )
  } else {
    if (is.na(endian)) {
      endian <- "little"
    }
    writeBin(input, raw(), size = datatype$nbytes, endian = endian)
  }
}


# -- Variable-length UTF-8 ------------------------
`codec_vlen-utf8_encode` <- function(input, ...) {
  raw_nvalues <- writeBin(length(input), raw(), size = 4L, endian = "little")
  # charToRaw() converts NA_character_ to "NA"
  raw_strings <- lapply(input, function(x) charToRaw(enc2utf8(x)))
  raw_string_lens <- lapply(lengths(raw_strings), function(x) {
    writeBin(x, raw(), size = 4L, endian = "little")
  })

  raw_vlen_utf8 <- c(
    raw_nvalues,
    unlist(mapply(
      function(len, str) c(len, str),
      raw_string_lens,
      raw_strings
    ))
  )
  return(raw_vlen_utf8)
}

`codec_vlen-utf8_decode` <- function(input, chunk_dim, ...) {
  .Call("codec_vlen_utf8_decode_c", input, chunk_dim, PACKAGE = "Rarr")
}

codec_sharding_indexed_decode <- function(
  input,
  shard_dim,
  datatype,
  fill_value,
  ...
) {
  config <- list(...)
  chunk_dim <- unlist(config$chunk_shape)
  index_shape <- c(2L, shard_dim / chunk_dim)
  index_length <- prod(index_shape)
  index_nbytes <- index_length * 8L
  # FIXME: any way for this to be cleaner?
  if (
    any(
      vapply(config$index_codecs, function(x) x$name, character(1L)) == "crc32c"
    )
  ) {
    index_nbytes <- index_nbytes + 4L
  }

  index_location <- config$index_location %||% "end"
  index_start <- if (index_location == "end") {
    length(input) - index_nbytes + 1L
  } else {
    1L
  }
  index_raw <- input[seq(index_start, length.out = index_nbytes)]

  index <- readBin(
    index_raw,
    what = "integer",
    n = index_length,
    size = 8L,
    endian = "little"
  )
  dim(index) <- index_shape
  index <- codec_transpose_decode(index, c(1L, rev(seq_along(dim(index))[-1L])))

  configured_decoders <- config$codecs |>
    setNames(vapply(
      config$codecs,
      function(x) x$name,
      FUN.VALUE = character(1L)
    )) |>
    .configure_codecs(operation = "decode")

  chunks_raw <- input[-seq(index_start, length.out = index_nbytes)]
  chunks <- apply(
    index,
    seq(2L, length(dim(index))),
    function(x) {
      chunk_offset <- x[[1L]]
      chunk_nbytes <- x[[2L]]
      if (chunk_nbytes <= 0L) {
        return()
      }
      # FIXME: offset by index nbytes if index is at the start
      chunk_raw <- chunks_raw[seq(
        chunk_offset + 1L,
        chunk_offset + chunk_nbytes
      )]
      # FIXME: Once stores are implemented, treat this as a memory store and use `read_data()` directly
      read_chunk(
        chunk_raw,
        chunk_dim = chunk_dim,
        decoders = configured_decoders,
        datatype = datatype,
        fill_value = fill_value
      )
    }
  )
  shard <- array(fill_value, dim = shard_dim)
  non_empty_coords <- which(
    asplit(index, 1L)[[2L]] > 0L,
    arr.ind = TRUE
  )
  # Merge chunks into shard
  for (i in seq_len(nrow(non_empty_coords))) {
    coords_in_shard <- non_empty_coords[i, ]
    index_in_result <- mapply(
      FUN = function(coord, chunk_dim) {
        seq((coord - 1L) * chunk_dim + 1L, length.out = chunk_dim)
      },
      coords_in_shard,
      chunk_dim = chunk_dim,
      SIMPLIFY = FALSE
    )
    chunk_to_insert <- drop(.extract_chunk(chunks, coords_in_shard))[[1L]]
    rlang::inject(shard[!!!index_in_result] <- chunk_to_insert) # nolint implicit_assignment_linter.
  }

  return(shard)
}
